### ISSUE TITLE
Merge "project" repo into monorepo

### ISSUE THREAD

**Issue by lassik** [scheme-containers/monorepo-old#2]
For reasons I cannot remember, we have two repos whose names suggest overlapping purposes:

* [project](https://github.com/scheme-containers/project)
* [monorepo](https://github.com/scheme-containers/monorepo) (this repo)

In the commit logs, the dates are:

* project: Dec 2019 until Dec 1, 2021
* monorepo: Dec 2, 2021 until today

It seems like we suddenly switched from project to monorepo on Dec 2, 2021 for unknown reasons.

Would you mind if we rebase monorepo on project and replace the project repo with a link to monorepo?

**Comment by weinholt** [comment]
I think `project` was just meant to be a place for issues and was created when we still had one repo per implementation (which was in turn because of how Docker Hub's automation worked). I have no opinion either way.

**Comment by rgherdt** [comment]
> I think `project` was just meant to be a place for issues and was created when we still had one repo per implementation (which was in turn because of how Docker Hub's automation worked). I have no opinion either way.

Would it make sense to put `project` inside `monorepo/doc` (with possibly some minor changes)?

**Comment by lassik** [comment]
[monorepo/scripts/](https://github.com/scheme-containers/monorepo/tree/master/scripts) and [project/generator/](https://github.com/scheme-containers/project/tree/master) do similar stuff - they auto-generate things based on S-expression descriptions of Scheme implementations. We should merge them.

Apart fom that, projects has just [the website](https://github.com/scheme-containers/project/tree/master/www).

IMHO, the alternatives which makes sense are:

1) Keep both the generators and the www in the same monorepo.
2) Have one repo for the generators and another repo for the www.

**Comment by lassik** [comment]
The current WWW is very bare-bones (and out of date). We might want to auto-generate the WWW too. For that reason, it might make sense to keep the WWW and the generators in the same repo.

EDIT: [Here it is](https://containers.scheme.org/) in all its glory :)

**Comment by lassik** [comment]
Since there have been no further comments and I have a lot on my plate, I will do the following:

* Copy the commits from monorepo into the project repo, on top of the commits that are already there. (git-filter-repo makes this easy.)
* Rename the present monorepo to "monorepo-old" and archive it (i.e. make it read-only - this setting can be reverted if needed.)
* Rename the present "project" repo into "monorepo". In other words, the new and improved "project" that combines the contents of both repos will take the place of the current "monorepo".
* As a side effect of the rename, GitHub will automatically set up a redirect from "project" to "monorepo".

There are GitHub workflows in the present "monorepo". Copying the git commits will copy the `.github/workflows` directory. But if some settings or authentication tokens need to be set elsewhere, that may have to be done manually.

It is my understanding that Docker Hub hasn't been triggered by new commits for a year or two.

**Comment by lassik** [comment]
NB: "project" currently has many issues whereas "monorepo" has only one PR and this one issue, so it's easier to make "project" the new base.

**Comment by lassik** [comment]
Done. [git-filter-repo](https://github.com/newren/git-filter-repo) is such a great tool!

The commit log [looks like this](https://github.com/scheme-containers/monorepo/commits/master). Please check that nothing is obviously wrong.

It goes without saying that if you do a `git pull` of monorepo now, it will fail due to the rewritten history.

If I don't hear any complaints in a couple of days, I'll close this issue and archive this repo (i.e. "monorepo-old").

**Comment by lassik** [comment]
@weinholt @rgherdt I assume that no news is good news. I'll close this issue and archive this repo.
